#!/bin/bash
#SBATCH --job-name=topo_worstfield
#SBATCH --output=logs_topo/worstfield_%A_%a.out
#SBATCH --error=logs_topo/worstfield_%A_%a.err

#SBATCH --time=48:00:00
#SBATCH --cpus-per-task=4
#SBATCH --mem=32G
#SBATCH --partition=clara
#SBATCH --exclude=clara[02,04-08]
#SBATCH --ntasks=1
#SBATCH --gres=gpu:1
# Cell 0 is excluded: it is the vanilla CycleGAN baseline, whose loss touches no
# field at all, so it is identical to the baseline already trained. See below.
#SBATCH --array=1-12

# The negative control for the field audit: train on the field the audit ranked
# WORST and see whether it does worse than the field it ranked best.
#
# The audit picks a setting by ranking 324 combinations on held-out validation
# tiles. That ranking is only worth the GPU it directs if it predicts something
# about training. This trains the other end of the same table. If the two ends
# perform alike, the ranking was not measuring anything that survives into
# training, and that is worth knowing before the field-selection protocol goes
# into a paper as a contribution.
#
# STEP 1 -- turn a finished audit's bottom row into an env file the sweep can
# source. Do this on the login node first, and LOOK at what it picked:
#
#   topo-worst-field --audit /work2/bz66izin-TopoCG/field_audit_mist \
#                    --out   /work2/bz66izin-TopoCG/field_worst_mist
#   topo-worst-field --audit /work2/bz66izin-TopoCG/field_audit_vs2 \
#                    --out   /work2/bz66izin-TopoCG/field_worst_vs2
#   topo-worst-field --audit /work2/bz66izin-TopoCG/field_audit_v2 \
#                    --out   /work2/bz66izin-TopoCG/field_worst_bci
#
# It prints the worst and best screening AUROC per marker. If they are already
# close, the control has little room to show anything and the experiment is
# answered before it starts.
#
# STEP 2 -- submit, with WORST_DIR pointing at what step 1 wrote:
#
#   MARKER=ER WORST_DIR=/work2/bz66izin-TopoCG/field_worst_mist \
#     sbatch --export=ALL sweep_worst_field.sh
#
#   # VS and BCI train on paula:
#   MARKER=VS  WORST_DIR=/work2/bz66izin-TopoCG/field_worst_vs2 \
#     TILES_VS=/work2/bz66izin-TopoCG/VS_tiles \
#     sbatch --export=ALL --partition=paula sweep_worst_field.sh
#   MARKER=BCI WORST_DIR=/work2/bz66izin-TopoCG/field_worst_bci \
#     sbatch --export=ALL --partition=paula sweep_worst_field.sh
#
# BOTH ph_cyc VARIANTS. PH_CYC_SPLIT selects which, and each gets its own
# output root so the two never resume one another:
#
#   PH_CYC_SPLIT=0 ... sbatch --export=ALL sweep_worst_field.sh
#   PH_CYC_SPLIT=1 ... sbatch --export=ALL --array=2,3,5,6,8,9,11,12 \
#                        sweep_worst_field.sh
#
# The split arm's array is the 8 cells with ph_cyc=1, because ph_cyc_split
# cannot reach a cell whose cycle weight is 0 -- cells 1, 4, 7 and 10 would
# repeat the merged arm exactly. Splitting also costs ~+50% persistence, so
# those cells overrun the 48h wall and need one resubmit; they resume from
# step_latest.pt on their own.
#
# WHY THE ARRAY STARTS AT 1. Cell 0 sets lambda_topo, ph_cyc and ph_trans all to
# zero, and topo_terms returns before touching a field module. The baseline is
# therefore bit-for-bit independent of which field was chosen, and the one in
# Outputs_<marker> is already the right comparison for this sweep. Running it
# again would spend 48h reproducing it.

MARKER=${MARKER:?set MARKER, e.g. MARKER=ER}
WORST_DIR=${WORST_DIR:?set WORST_DIR to what topo-worst-field wrote}

env_file="${WORST_DIR}/recommended_${MARKER}.env"
if [ ! -f "$env_file" ]; then
    echo "ERROR: ${env_file} does not exist" >&2
    echo "Run topo-worst-field --audit <the audit> --out ${WORST_DIR} first." >&2
    exit 1
fi
# Refuse to run against the real audit: its recommended_<M>.env holds the
# WINNER, and sourcing that here would silently retrain the main sweep into a
# directory labelled as the control.
if ! grep -q "Generated by topo-worst-field" "$env_file"; then
    echo "ERROR: ${env_file} was not written by topo-worst-field." >&2
    echo "It looks like a real audit recommendation -- training it here would" >&2
    echo "retrain the main sweep into a directory labelled as the control." >&2
    echo "Pass WORST_DIR=<what topo-worst-field --out wrote>." >&2
    exit 1
fi

# _sweep_common.sh sources ${AUDIT_DIR}/recommended_${MARKER}.env, which is
# exactly the shape topo-worst-field writes. Reusing that path is the point:
# the control differs from the real sweep in the values it reads, and in
# nothing else.
AUDIT_DIR="$WORST_DIR"

PH_CYC_SPLIT=${PH_CYC_SPLIT:-0}
case "$PH_CYC_SPLIT" in
    0) variant="cycmerged" ;;
    1) variant="cycsplit" ;;
    *) echo "ERROR: PH_CYC_SPLIT must be 0 or 1, got '${PH_CYC_SPLIT}'" >&2; exit 1 ;;
esac

# Its own root, per variant: RUN_NAME depends only on the grid cell, so sharing
# a root with the real sweep would resume that run under a different field.
MARKER_LC=$(echo "$MARKER" | tr 'A-Z' 'a-z')
BASE=${BASE:-/work2/bz66izin-TopoCG/Outputs_${MARKER_LC}_worstfield_${variant}}

SLURM_DIR=${REPO:-${SLURM_SUBMIT_DIR:-$PWD}}
[ -f "${SLURM_DIR}/_sweep_common.sh" ] || SLURM_DIR="${SLURM_DIR}/slurm"

echo "FIELD CONTROL: training on the audit's worst-ranked field"
echo "  env file    ${env_file}"
echo "  ph_cyc      ${variant} (PH_CYC_SPLIT=${PH_CYC_SPLIT})"
echo "  output root ${BASE}"
sed 's/^/    /' "$env_file"

source "${SLURM_DIR}/_sweep_common.sh"
